// 汽车品牌统一配置文件
// 包含完整的品牌列表、映射关系和导出函数

// 品牌映射关系（中文名 → URL英文标识）
export const brandMapping = {
  '豐田 TOYOTA': 'toyota',
  '平治 MERCEDES-BENZ': 'mercedes-benz',
  '本田 HONDA': 'honda',
  '寶馬 BMW': 'bmw',
  '保時捷 PORSCHE': 'porsche',
  '奧迪 AUDI': 'audi',
  '日產 NISSAN': 'nissan',
  '特斯拉 TESLA': 'tesla',
  '凌志 LEXUS': 'lexus',
  '五十鈴 ISUZU': 'isuzu',
  '福士 VOLKSWAGEN': 'volkswagen',
  '越野路華 LAND ROVER': 'land-rover',
  '鈴木 SUZUKI': 'suzuki',
  '富士 SUBARU': 'subaru',
  '萬事得 MAZDA': 'mazda',
  '三菱 MITSUBISHI': 'mitsubishi',
  '起亞 KIA': 'kia',
  '法拉利 FERRARI': 'ferrari',
  '迷你 MINI': 'mini',
  '現代 HYUNDAI': 'hyundai',
  '福特 FORD': 'ford',
  '賓利 BENTLEY': 'bentley',
  '富豪 VOLVO': 'volvo',
  '日野 HINO': 'hino',
  '林寶堅尼 LAMBORGHINI': 'lamborghini',
  '瑪莎拉蒂 MASERATI': 'maserati',
  '勞斯萊斯 ROLLS ROYCE': 'rolls-royce',
  '麥拿倫 MCLAREN': 'mclaren',
  '積架 JAGUAR': 'jaguar',
  '標緻 PEUGEOT': 'peugeot',
  '比亞迪 BYD': 'byd',
  '阿士頓馬田 ASTON MARTIN': 'aston-martin',
  '極品 ACURA': 'acura',
  '蓮花 LOTUS': 'lotus',
  '大發 DAIHATSU': 'daihatsu',
  '愛快 ALFAROMEO': 'alfaromeo',
  '雷諾 RENAULT': 'renault',
  '東風 DONGFENG': 'dongfeng',
  '路華 ROVER': 'rover',
  '先進 CITROEN': 'citroen',
  '雙龍 SSANGYONG': 'ssangyong',
  '快意 FIAT': 'fiat',
  '福田 FOTON': 'foton',
  '江淮 JAC': 'jac',
  '大實力 UD': 'ud',
  '猛獅 MAN': 'man',
  '中國重汽 SINOTRUK': 'sinotruk',
  '歐寶 OPEL': 'opel',
  '歐霸 IVECO': 'iveco',
  '紳寶 SAAB': 'saab',
  'MAXUS': 'maxus',
  'SMART': 'smart',
  'INFINITI': 'infiniti',
  'JEEP': 'jeep',
  'MG': 'mg',
  'SCANIA': 'scania',
  '任何 ANY': 'any'
}

// 完整品牌列表（包含统计数据，用于搜索页面）
export const brandsListWithCount = [
  { brand: "豐田 TOYOTA", count: 4389, label: "豐田 TOYOTA" },
  { brand: "平治 MERCEDES-BENZ", count: 1864, label: "平治 MERCEDES-BENZ" },
  { brand: "本田 HONDA", count: 1673, label: "本田 HONDA" },
  { brand: "寶馬 BMW", count: 1412, label: "寶馬 BMW" },
  { brand: "保時捷 PORSCHE", count: 770, label: "保時捷 PORSCHE" },
  { brand: "奧迪 AUDI", count: 505, label: "奧迪 AUDI" },
  { brand: "日產 NISSAN", count: 496, label: "日產 NISSAN" },
  { brand: "特斯拉 TESLA", count: 465, label: "特斯拉 TESLA" },
  { brand: "任何 ANY", count: 444, label: "任何 ANY" },
  { brand: "凌志 LEXUS", count: 375, label: "凌志 LEXUS" },
  { brand: "五十鈴 ISUZU", count: 372, label: "五十鈴 ISUZU" },
  { brand: "福士 VOLKSWAGEN", count: 302, label: "福士 VOLKSWAGEN" },
  { brand: "越野路華 LAND ROVER", count: 265, label: "越野路華 LAND ROVER" },
  { brand: "鈴木 SUZUKI", count: 262, label: "鈴木 SUZUKI" },
  { brand: "富士 SUBARU", count: 248, label: "富士 SUBARU" },
  { brand: "萬事得 MAZDA", count: 232, label: "萬事得 MAZDA" },
  { brand: "三菱 MITSUBISHI", count: 230, label: "三菱 MITSUBISHI" },
  { brand: "起亞 KIA", count: 229, label: "起亞 KIA" },
  { brand: "法拉利 FERRARI", count: 203, label: "法拉利 FERRARI" },
  { brand: "迷你 MINI", count: 182, label: "迷你 MINI" },
  { brand: "現代 HYUNDAI", count: 174, label: "現代 HYUNDAI" },
  { brand: "福特 FORD", count: 131, label: "福特 FORD" },
  { brand: "賓利 BENTLEY", count: 114, label: "賓利 BENTLEY" },
  { brand: "富豪 VOLVO", count: 112, label: "富豪 VOLVO" },
  { brand: "日野 HINO", count: 99, label: "日野 HINO" },
  { brand: "林寶堅尼 LAMBORGHINI", count: 96, label: "林寶堅尼 LAMBORGHINI" },
  { brand: "瑪莎拉蒂 MASERATI", count: 95, label: "瑪莎拉蒂 MASERATI" },
  { brand: "勞斯萊斯 ROLLS ROYCE", count: 69, label: "勞斯萊斯 ROLLS ROYCE" },
  { brand: "麥拿倫 MCLAREN", count: 69, label: "麥拿倫 MCLAREN" },
  { brand: "積架 JAGUAR", count: 54, label: "積架 JAGUAR" },
  { brand: "標緻 PEUGEOT", count: 48, label: "標緻 PEUGEOT" },
  { brand: "比亞迪 BYD", count: 42, label: "比亞迪 BYD" },
  { brand: "阿士頓馬田 ASTON MARTIN", count: 39, label: "阿士頓馬田 ASTON MARTIN" },
  { brand: "極品 ACURA", count: 35, label: "極品 ACURA" },
  { brand: "MAXUS", count: 37, label: "MAXUS" },
  { brand: "蓮花 LOTUS", count: 35, label: "蓮花 LOTUS" },
  { brand: "SMART", count: 34, label: "SMART" },
  { brand: "大發 DAIHATSU", count: 31, label: "大發 DAIHATSU" },
  { brand: "愛快 ALFAROMEO", count: 31, label: "愛快 ALFAROMEO" },
  { brand: "雷諾 RENAULT", count: 29, label: "雷諾 RENAULT" },
  { brand: "INFINITI", count: 26, label: "INFINITI" },
  { brand: "JEEP", count: 26, label: "JEEP" },
  { brand: "東風 DONGFENG", count: 23, label: "東風 DONGFENG" },
  { brand: "路華 ROVER", count: 20, label: "路華 ROVER" },
  { brand: "先進 CITROEN", count: 19, label: "先進 CITROEN" },
  { brand: "雙龍 SSANGYONG", count: 19, label: "雙龍 SSANGYONG" },
  { brand: "MG", count: 17, label: "MG" },
  { brand: "快意 FIAT", count: 17, label: "快意 FIAT" },
  { brand: "SCANIA", count: 14, label: "SCANIA" },
  { brand: "福田 FOTON", count: 8, label: "福田 FOTON" },
  { brand: "江淮 JAC", count: 7, label: "江淮 JAC" },
  { brand: "大實力 UD", count: 6, label: "大實力 UD" },
  { brand: "猛獅 MAN", count: 5, label: "猛獅 MAN" },
  { brand: "中國重汽 SINOTRUK", count: 3, label: "中國重汽 SINOTRUK" },
  { brand: "歐寶 OPEL", count: 1, label: "歐寶 OPEL" },
  { brand: "歐霸 IVECO", count: 2, label: "歐霸 IVECO" },
  { brand: "紳寶 SAAB", count: 1, label: "紳寶 SAAB" }
]

// 简单品牌列表（用于发布页面）
export const brandsListSimple = [
  { label: "豐田 TOYOTA", value: "豐田 TOYOTA" },
  { label: "平治 MERCEDES-BENZ", value: "平治 MERCEDES-BENZ" },
  { label: "本田 HONDA", value: "本田 HONDA" },
  { label: "寶馬 BMW", value: "寶馬 BMW" },
  { label: "保時捷 PORSCHE", value: "保時捷 PORSCHE" },
  { label: "奧迪 AUDI", value: "奧迪 AUDI" },
  { label: "日產 NISSAN", value: "日產 NISSAN" },
  { label: "特斯拉 TESLA", value: "特斯拉 TESLA" },
  { label: "凌志 LEXUS", value: "凌志 LEXUS" },
  { label: "五十鈴 ISUZU", value: "五十鈴 ISUZU" },
  { label: "福士 VOLKSWAGEN", value: "福士 VOLKSWAGEN" },
  { label: "越野路華 LAND ROVER", value: "越野路華 LAND ROVER" },
  { label: "鈴木 SUZUKI", value: "鈴木 SUZUKI" },
  { label: "富士 SUBARU", value: "富士 SUBARU" },
  { label: "萬事得 MAZDA", value: "萬事得 MAZDA" },
  { label: "三菱 MITSUBISHI", value: "三菱 MITSUBISHI" },
  { label: "起亞 KIA", value: "起亞 KIA" },
  { label: "法拉利 FERRARI", value: "法拉利 FERRARI" },
  { label: "迷你 MINI", value: "迷你 MINI" },
  { label: "現代 HYUNDAI", value: "現代 HYUNDAI" },
  { label: "福特 FORD", value: "福特 FORD" },
  { label: "賓利 BENTLEY", value: "賓利 BENTLEY" },
  { label: "富豪 VOLVO", value: "富豪 VOLVO" },
  { label: "日野 HINO", value: "日野 HINO" },
  { label: "林寶堅尼 LAMBORGHINI", value: "林寶堅尼 LAMBORGHINI" },
  { label: "瑪莎拉蒂 MASERATI", value: "瑪莎拉蒂 MASERATI" },
  { label: "勞斯萊斯 ROLLS ROYCE", value: "勞斯萊斯 ROLLS ROYCE" },
  { label: "麥拿倫 MCLAREN", value: "麥拿倫 MCLAREN" },
  { label: "積架 JAGUAR", value: "積架 JAGUAR" },
  { label: "標緻 PEUGEOT", value: "標緻 PEUGEOT" },
  { label: "比亞迪 BYD", value: "比亞迪 BYD" },
  { label: "阿士頓馬田 ASTON MARTIN", value: "阿士頓馬田 ASTON MARTIN" },
  { label: "極品 ACURA", value: "極品 ACURA" },
  { label: "MAXUS", value: "MAXUS" },
  { label: "蓮花 LOTUS", value: "蓮花 LOTUS" },
  { label: "SMART", value: "SMART" },
  { label: "大發 DAIHATSU", value: "大發 DAIHATSU" },
  { label: "愛快 ALFAROMEO", value: "愛快 ALFAROMEO" },
  { label: "雷諾 RENAULT", value: "雷諾 RENAULT" },
  { label: "INFINITI", value: "INFINITI" },
  { label: "JEEP", value: "JEEP" },
  { label: "東風 DONGFENG", value: "東風 DONGFENG" },
  { label: "路華 ROVER", value: "路華 ROVER" },
  { label: "先進 CITROEN", value: "先進 CITROEN" },
  { label: "雙龍 SSANGYONG", value: "雙龍 SSANGYONG" },
  { label: "MG", value: "MG" },
  { label: "快意 FIAT", value: "快意 FIAT" },
  { label: "SCANIA", value: "SCANIA" },
  { label: "福田 FOTON", value: "福田 FOTON" },
  { label: "江淮 JAC", value: "江淮 JAC" },
  { label: "大實力 UD", value: "大實力 UD" },
  { label: "猛獅 MAN", value: "猛獅 MAN" },
  { label: "中國重汽 SINOTRUK", value: "中國重汽 SINOTRUK" },
  { label: "歐寶 OPEL", value: "歐寶 OPEL" },
  { label: "歐霸 IVECO", value: "歐霸 IVECO" },
  { label: "紳寶 SAAB", value: "紳寶 SAAB" },
  { label: "任何 ANY", value: "任何 ANY" }
]

// 工具函数：反向映射（URL英文标识 → 完整品牌名）
export const getBrandFromUrl = (urlBrand) => {
  // 查找对应的完整品牌名
  for (const [key, value] of Object.entries(brandMapping)) {
    if (value === urlBrand.toLowerCase()) {
      return key
    }
  }
  // 如果没找到，返回原值
  return urlBrand
}

// 工具函数：正向映射（完整品牌名 → URL英文标识）
export const getBrandParam = (fullBrandName) => {
  return brandMapping[fullBrandName] || fullBrandName.toLowerCase()
}